name: isolated_worker
description: A singleton isolated worker for Flutter (Isolate) and Web (Web Worker).
version: 0.1.3
repository: https://www.github.com/iandis/isolated_worker
issue_tracker: https://www.github.com/iandis/isolated_worker/issues

environment:
  sdk: ^3.7.0

dependencies:
  meta: ^1.7.0
  web: ^1.1.1

dev_dependencies:
  lint: ^2.8.0
  test: ^1.16.0
